export interface City {
  id: string;
  name: string;
  stateId: string;
}

export interface State {
  id: string;
  name: string;
  abbreviation: string;
}

export const brazilStates: State[] = [
  { id: "AC", name: "Acre", abbreviation: "AC" },
  { id: "AL", name: "Alagoas", abbreviation: "AL" },
  { id: "AP", name: "Amapá", abbreviation: "AP" },
  { id: "AM", name: "Amazonas", abbreviation: "AM" },
  { id: "BA", name: "Bahia", abbreviation: "BA" },
  { id: "CE", name: "Ceará", abbreviation: "CE" },
  { id: "DF", name: "Distrito Federal", abbreviation: "DF" },
  { id: "ES", name: "Espírito Santo", abbreviation: "ES" },
  { id: "GO", name: "Goiás", abbreviation: "GO" },
  { id: "MA", name: "Maranhão", abbreviation: "MA" },
  { id: "MT", name: "Mato Grosso", abbreviation: "MT" },
  { id: "MS", name: "Mato Grosso do Sul", abbreviation: "MS" },
  { id: "MG", name: "Minas Gerais", abbreviation: "MG" },
  { id: "PA", name: "Pará", abbreviation: "PA" },
  { id: "PB", name: "Paraíba", abbreviation: "PB" },
  { id: "PR", name: "Paraná", abbreviation: "PR" },
  { id: "PE", name: "Pernambuco", abbreviation: "PE" },
  { id: "PI", name: "Piauí", abbreviation: "PI" },
  { id: "RJ", name: "Rio de Janeiro", abbreviation: "RJ" },
  { id: "RN", name: "Rio Grande do Norte", abbreviation: "RN" },
  { id: "RS", name: "Rio Grande do Sul", abbreviation: "RS" },
  { id: "RO", name: "Rondônia", abbreviation: "RO" },
  { id: "RR", name: "Roraima", abbreviation: "RR" },
  { id: "SC", name: "Santa Catarina", abbreviation: "SC" },
  { id: "SP", name: "São Paulo", abbreviation: "SP" },
  { id: "SE", name: "Sergipe", abbreviation: "SE" },
  { id: "TO", name: "Tocantins", abbreviation: "TO" },
];

export const brazilCities: Record<string, string[]> = {
  AC: [
    "Rio Branco",
    "Cruzeiro do Sul",
    "Sena Madureira",
    "Tarauacá",
    "Feijó",
    "Brasiléia",
    "Plácido de Castro",
    "Xapuri",
    "Epitaciolândia",
    "Mâncio Lima",
    "Senador Guiomard",
    "Rodrigues Alves",
    "Acrelândia",
    "Capixaba",
    "Bujari",
    "Porto Walter",
    "Jordão",
    "Manoel Urbano",
    "Santa Rosa do Purus",
    "Marechal Thaumaturgo",
    "Assis Brasil",
    "Porto Acre",
  ],
  AL: [
    "Maceió",
    "Arapiraca",
    "Rio Largo",
    "Palmeira dos Índios",
    "União dos Palmares",
    "Penedo",
    "Coruripe",
    "São Miguel dos Campos",
    "Santana do Ipanema",
    "Delmiro Gouveia",
    "Campo Alegre",
    "Murici",
    "Messias",
    "Marechal Deodoro",
    "Pilar",
    "São Luís do Quitunde",
    "Viçosa",
    "Girau do Ponciano",
    "Matriz de Camaragibe",
    "São Sebastião",
    "Água Branca",
    "Anadia",
    "Atalaia",
    "Barra de Santo Antônio",
    "Barra de São Miguel",
    "Batalha",
    "Belém",
    "Belo Monte",
    "Boca da Mata",
    "Branquinha",
    "Cacimbinhas",
    "Cajueiro",
    "Campestre",
    "Canapi",
    "Capela",
    "Carneiros",
    "Chã Preta",
    "Coité do Nóia",
    "Colônia Leopoldina",
    "Coqueiro Seco",
    "Craíbas",
    "Dois Riachos",
    "Estrela de Alagoas",
    "Feira Grande",
    "Feliz Deserto",
    "Flexeiras",
    "Ibateguara",
    "Igaci",
    "Igreja Nova",
    "Inhapi",
    "Jacaré dos Homens",
    "Jacuípe",
    "Japaratinga",
    "Jaramataia",
    "Jequiá da Praia",
    "Joaquim Gomes",
    "Jundiá",
    "Junqueiro",
    "Lagoa da Canoa",
    "Limoeiro de Anadia",
    "Maragogi",
    "Mar Vermelho",
    "Mata Grande",
    "Minador do Negrão",
    "Monteirópolis",
    "Novo Lino",
    "Olho d'Água das Flores",
    "Olho d'Água do Casado",
    "Olho d'Água Grande",
    "Olivença",
    "Ouro Branco",
    "Palestina",
    "Pão de Açúcar",
    "Pariconha",
    "Paripueira",
    "Passo de Camaragibe",
    "Paulo Jacinto",
    "Piaçabuçu",
    "Piranhas",
    "Poço das Trincheiras",
    "Porto Calvo",
    "Porto de Pedras",
    "Porto Real do Colégio",
    "Quebrangulo",
    "Rio Branco",
    "Roteiro",
    "Santa Luzia do Norte",
    "Santana do Mundaú",
    "São Brás",
    "São José da Laje",
    "São José da Tapera",
    "Satuba",
    "Senador Rui Palmeira",
    "Tanque d'Arca",
    "Taquarana",
    "Teotônio Vilela",
    "Traipu",
  ],
  AP: [
    "Macapá",
    "Santana",
    "Laranjal do Jari",
    "Oiapoque",
    "Mazagão",
    "Porto Grande",
    "Pedra Branca do Amapari",
    "Vitória do Jari",
    "Tartarugalzinho",
    "Amapá",
    "Ferreira Gomes",
    "Cutias",
    "Itaubal",
    "Calçoene",
    "Pracuúba",
    "Serra do Navio",
  ],
  AM: [
    "Manaus",
    "Parintins",
    "Itacoatiara",
    "Manacapuru",
    "Coari",
    "Tefé",
    "Tabatinga",
    "Maués",
    "São Paulo de Olivença",
    "Humaitá",
    "Lábrea",
    "Iranduba",
    "Benjamin Constant",
    "Manicoré",
    "Carauari",
    "Eirunepé",
    "Rio Preto da Eva",
    "Presidente Figueiredo",
    "Barcelos",
    "Novo Airão",
    "Boca do Acre",
    "Careiro",
    "Autazes",
    "São Gabriel da Cachoeira",
    "Fonte Boa",
    "Tonantins",
    "Urucurituba",
    "Nhamundá",
    "Silves",
    "Beruri",
    "Anori",
    "Anamã",
    "Caapiranga",
    "Codajás",
    "Tapauá",
    "Jutaí",
    "Uarini",
    "Alvarães",
    "Atalaia do Norte",
    "Santo Antônio do Içá",
    "Careiro da Várzea",
    "Nova Olinda do Norte",
    "Borba",
    "Novo Aripuanã",
    "Apuí",
    "Maraã",
    "Envira",
    "Guajará",
    "Ipixuna",
    "Pauini",
    "Canutama",
    "Itamarati",
    "Juruá",
    "Japurá",
    "Barreirinha",
    "Boa Vista do Ramos",
    "São Sebastião do Uatumã",
    "Urucará",
    "Amaturá",
    "Santa Isabel do Rio Negro",
    "Carauari",
  ],
  BA: [
    "Salvador",
    "Feira de Santana",
    "Vitória da Conquista",
    "Camaçari",
    "Juazeiro",
    "Ilhéus",
    "Itabuna",
    "Lauro de Freitas",
    "Jequié",
    "Teixeira de Freitas",
    "Alagoinhas",
    "Porto Seguro",
    "Simões Filho",
    "Paulo Afonso",
    "Eunápolis",
    "Candeias",
    "Guanambi",
    "Jacobina",
    "Serrinha",
    "Senhor do Bonfim",
    "Dias d'Ávila",
    "Luís Eduardo Magalhães",
    "Itapetinga",
    "Irecê",
    "Campo Formoso",
    "Casa Nova",
    "Brumado",
    "Bom Jesus da Lapa",
    "Conceição do Coité",
    "Itamaraju",
    "Valença",
    "Ribeira do Pombal",
    "Esplanada",
    "Itaberaba",
    "Cruz das Almas",
    "Ipirá",
    "Santo Antônio de Jesus",
    "Euclides da Cunha",
    "Araci",
    "Tucano",
    "Catu",
    "Jaguaquara",
    "Monte Santo",
    "Santo Amaro",
    "Barra",
    "Sobradinho",
    "Una",
    "Pojuca",
    "Madre de Deus",
    "Vera Cruz",
  ],
  CE: [
    "Fortaleza",
    "Caucaia",
    "Juazeiro do Norte",
    "Maracanaú",
    "Sobral",
    "Crato",
    "Itapipoca",
    "Maranguape",
    "Iguatu",
    "Quixadá",
    "Canindé",
    "Aquiraz",
    "Pacajus",
    "Crateús",
    "Russas",
    "Aracati",
    "Cascavel",
    "Pacatuba",
    "Icó",
    "Horizonte",
    "Camocim",
    "Morada Nova",
    "Acaraú",
    "Viçosa do Ceará",
    "Barbalha",
    "Limoeiro do Norte",
    "Tianguá",
    "Assaré",
    "Tauá",
    "Santa Quitéria",
    "Baturité",
    "Quixeramobim",
    "Eusébio",
    "São Gonçalo do Amarante",
    "Itaitinga",
    "Cariré",
    "Grajau",
    "Mauriti",
    "Trairi",
    "Granja",
    "Boa Viagem",
    "Ubajara",
    "Jijoca de Jericoacoara",
    "Paraipaba",
    "Pentecoste",
    "São Benedito",
    "Guaraciaba do Norte",
    "Croatá",
    "Marco",
    "Pacoti",
  ],
  DF: [
    "Brasília",
    "Gama",
    "Taguatinga",
    "Ceilândia",
    "Sobradinho",
    "Planaltina",
    "Paranoá",
    "Núcleo Bandeirante",
    "Brazlândia",
    "Guará",
    "Cruzeiro",
    "Samambaia",
    "Santa Maria",
    "São Sebastião",
    "Recanto das Emas",
    "Lago Sul",
    "Riacho Fundo",
    "Águas Claras",
    "Riacho Fundo II",
    "Sudoeste/Octogonal",
    "Varjão",
    "Park Way",
    "SCIA",
    "Sobradinho II",
    "Jardim Botânico",
    "Itapoã",
    "SIA",
    "Vicente Pires",
    "Fercal",
  ],
  ES: [
    "Vila Velha",
    "Serra",
    "Cariacica",
    "Vitória",
    "Cachoeiro de Itapemirim",
    "Linhares",
    "São Mateus",
    "Colatina",
    "Guarapari",
    "Aracruz",
    "Viana",
    "Nova Venécia",
    "Barra de São Francisco",
    "Santa Teresa",
    "São Gabriel da Palha",
    "Conceição da Barra",
    "Castelo",
    "Marataízes",
    "Anchieta",
    "Alegre",
    "Baixo Guandu",
    "Bom Jesus do Norte",
    "Brejetuba",
    "Conceição do Castelo",
    "Domingos Martins",
    "Ecoporanga",
    "Fundão",
    "Governador Lindenberg",
    "Guaçuí",
    "Ibatiba",
    "Ibitirama",
    "Iconha",
    "Irupi",
    "Itaguaçu",
    "Itapemirim",
    "Itarana",
    "Iúna",
    "Jaguaré",
    "Jerônimo Monteiro",
    "João Neiva",
    "Laranja da Terra",
    "Marechal Floriano",
    "Marilândia",
    "Mimoso do Sul",
    "Montanha",
    "Mucurici",
    "Muniz Freire",
    "Muqui",
    "Pancas",
    "Pedro Canário",
    "Pinheiros",
    "Piúma",
    "Ponto Belo",
    "Presidente Kennedy",
    "Rio Bananal",
    "Rio Novo do Sul",
    "Santa Leopoldina",
    "Santa Maria de Jetibá",
    "São Domingos do Norte",
    "São José do Calçado",
    "São Roque do Canaã",
    "Sooretama",
    "Vargem Alta",
    "Venda Nova do Imigrante",
    "Vila Pavão",
    "Vila Valério",
  ],
  GO: [
    "Goiânia",
    "Aparecida de Goiânia",
    "Anápolis",
    "Rio Verde",
    "Luziânia",
    "Águas Lindas de Goiás",
    "Valparaíso de Goiás",
    "Trindade",
    "Formosa",
    "Novo Gama",
    "Itumbiara",
    "Senador Canedo",
    "Catalão",
    "Jataí",
    "Planaltina",
    "Caldas Novas",
    "Santo Antônio do Descoberto",
    "Goianésia",
    "Cidade Ocidental",
    "Mineiros",
    "Cristalina",
    "Inhumas",
    "Ipatinga",
    "Alexânia",
    "Ceres",
    "Rubiataba",
    "Goiás",
    "Quirinópolis",
    "Porangatu",
    "Padre Bernardo",
    "Cocalzinho de Goiás",
    "Piracanjuba",
    "Bela Vista de Goiás",
    "Nerópolis",
    "Abadiânia",
    "Hidrolândia",
    "Jussara",
    "Pires do Rio",
    "Orizona",
    "Jaraguá",
    "Pontalina",
    "Morrinhos",
    "São Luís de Montes Belos",
    "Palmeiras de Goiás",
    "Ipameri",
    "Iporá",
    "Cachoeira Dourada",
    "Corumbaíba",
    "Pirenópolis",
  ],
  MA: [
    "São Luís",
    "Imperatriz",
    "São José de Ribamar",
    "Timon",
    "Caxias",
    "Codó",
    "Paço do Lumiar",
    "Açailândia",
    "Bacabal",
    "Balsas",
    "Barra do Corda",
    "Chapadinha",
    "Santa Inês",
    "Pinheiro",
    "Pedreiras",
    "Presidente Dutra",
    "Tutóia",
    "Coroatá",
    "Grajaú",
    "Itapecuru Mirim",
    "Zé Doca",
    "Carolina",
    "São João dos Patos",
    "Viana",
    "Rosário",
    "Matões",
    "Lago da Pedra",
    "Colinas",
    "São Bento",
    "Estreito",
    "Riachão",
    "Miranda do Norte",
    "Barreirinhas",
    "Coelho Neto",
    "São Domingos do Maranhão",
    "Buriticupu",
    "Porto Franco",
    "Primeira Cruz",
    "São Vicente Ferrer",
    "Humberto de Campos",
    "Alcântara",
    "Araioses",
    "Brejo",
    "São Mateus do Maranhão",
    "Vitória do Mearim",
    "Governador Nunes Freire",
    "Santa Rita",
    "Buriti",
    "Tuntum",
    "Mirador",
  ],
  MT: [
    "Cuiabá",
    "Várzea Grande",
    "Rondonópolis",
    "Sinop",
    "Tangará da Serra",
    "Cáceres",
    "Sorriso",
    "Lucas do Rio Verde",
    "Barra do Garças",
    "Primavera do Leste",
    "Alta Floresta",
    "Campo Verde",
    "Poconé",
    "Nova Mutum",
    "Colíder",
    "Mirassol d'Oeste",
    "Diamantino",
    "Guarantã do Norte",
    "Matupá",
    "Peixoto de Azevedo",
    "Campo Novo do Parecis",
    "Pontes e Lacerda",
    "Juína",
    "Sapezal",
    "Nova Brasilândia",
    "Água Boa",
    "Confresa",
    "Juara",
    "Canarana",
    "Araputanga",
    "São José do Rio Claro",
    "Brasnorte",
    "Arenápolis",
    "Chapada dos Guimarães",
    "Rosário Oeste",
    "Jaciara",
    "Querência",
    "Pedra Preta",
    "Vila Rica",
    "Santo Antônio do Leverger",
    "Nobres",
    "Bom Jesus do Araguaia",
    "Paranaíta",
    "Feliz Natal",
    "São José dos Quatro Marcos",
    "Nortelândia",
    "Itiquira",
    "Cotriguaçu",
    "Ribeirão Cascalheira",
    "Dom Aquino",
  ],
  MS: [
    "Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Naviraí",
    "Nova Andradina",
    "Sidrolândia",
    "Maracaju",
    "São Gabriel do Oeste",
    "Coxim",
    "Aquidauana",
    "Paranaíba",
    "Amambai",
    "Ribas do Rio Pardo",
    "Bataguassu",
    "Caarapó",
    "Bonito",
    "Anastácio",
    "Chapadão do Sul",
    "Aparecida do Taboado",
    "Jardim",
    "Cassilândia",
    "Miranda",
    "Rio Brilhante",
    "Costa Rica",
    "Iguatemi",
    "Ivinhema",
    "Terenos",
    "Bela Vista",
    "Mundo Novo",
    "Ladário",
    "Nova Alvorada do Sul",
    "Rochedo",
    "Angélica",
    "Eldorado",
    "Glória de Dourados",
    "Itaporã",
    "Juti",
    "Brasilândia",
    "Água Clara",
    "Bandeirantes",
    "Bodoquena",
    "Caracol",
    "Coronel Sapucaia",
    "Deodápolis",
    "Dois Irmãos do Buriti",
    "Fátima do Sul",
    "Guia Lopes da Laguna",
    "Inocência",
    "Itaquiraí",
    "Japorã",
    "Jaraguari",
    "Jateí",
    "Laguna Carapã",
    "Maracaju",
    "Nioaque",
    "Nova Alvorada do Sul",
    "Pedro Gomes",
    "Porto Murtinho",
    "Rio Negro",
    "Rio Verde de Mato Grosso",
    "Santa Rita do Pardo",
    "São Gabriel do Oeste",
    "Selvíria",
    "Sete Quedas",
    "Sonora",
    "Tacuru",
    "Taquarussu",
    "Vicentina",
  ],
  MG: [
    "Belo Horizonte",
    "Uberlândia",
    "Contagem",
    "Juiz de Fora",
    "Betim",
    "Montes Claros",
    "Ribeirão das Neves",
    "Uberaba",
    "Governador Valadares",
    "Ipatinga",
    "Sete Lagoas",
    "Divinópolis",
    "Santa Luzia",
    "Ibirité",
    "Poços de Caldas",
    "Patos de Minas",
    "Pouso Alegre",
    "Teófilo Otoni",
    "Barbacena",
    "Sabará",
    "Vespasiano",
    "Conselheiro Lafaiete",
    "Varginha",
    "Itabira",
    "Passos",
    "Coronel Fabriciano",
    "Muriaé",
    "Ituiutaba",
    "Araguari",
    "Ubá",
    "Lafaiete",
    "Itajubá",
    "Pará de Minas",
    "Paracatu",
    "Caratinga",
    "Nova Lima",
    "Nova Serrana",
    "São João del Rei",
    "Patrocínio",
    "Timóteo",
    "Manhuaçu",
    "Unaí",
    "Curvelo",
    "Alfenas",
    "João Monlevade",
    "Três Corações",
    "Viçosa",
    "Cataguases",
    "Ouro Preto",
    "Janaúba",
    "São Sebastião do Paraíso",
    "Janúaria",
    "Formiga",
    "Esmeraldas",
    "Pedro Leopoldo",
    "Ponte Nova",
    "Frutal",
    "Três Pontas",
    "São Francisco",
    "Pirapora",
    "Campo Belo",
    "Leopoldina",
    "Congonhas",
    "Guaxupé",
    "Lagoa Santa",
    "Mariana",
    "Itaúna",
    "Boa Esperança",
    "Passos",
    "Lavras",
    "Itapecerica",
    "Igarapé",
    "Nanuque",
    "Oliveira",
    "Santo Antônio do Monte",
    "Tupaciguara",
    "João Pinheiro",
    "Machado",
    "Visconde do Rio Branco",
    "Vazante",
    "Carangola",
    "São Lourenço",
    "Arcos",
    "Além Paraíba",
    "Caxambu",
    "Monte Carmelo",
    "Paraguaçu",
    "Bambuí",
    "Sacramento",
    "Conceição do Mato Dentro",
    "Aimorés",
    "Caeté",
    "São Gotardo",
    "Andradas",
    "Buritis",
    "Bias Fortes",
    "Brasília de Minas",
    "Campos Altos",
    "Capelinha",
    "Carneirinho",
    "Cássia",
    "Centralina",
    "Cláudio",
    "Coração de Jesus",
    "Coromandel",
    "Delfim Moreira",
    "Diamantina",
    "Espinosa",
    "Extrema",
    "Fama",
    "Francisco Sá",
    "Fronteira",
    "Grão Mogol",
    "Guaranésia",
    "Ibiá",
    "Inhapim",
    "Ipanema",
    "Itanhandu",
    "Itaobim",
    "Iturama",
    "Jacutinga",
    "Jequitinhonha",
    "Lima Duarte",
    "Malacacheta",
    "Mantena",
    "Mar de Espanha",
    "Mateus Leme",
    "Medina",
    "Monte Santo de Minas",
    "Nepomuceno",
    "Nova Era",
    "Novo Cruzeiro",
    "Ouro Fino",
    "Perdizes",
    "Piumhi",
    "Pompéu",
    "Porteirinha",
    "Presidente Olegário",
    "Raul Soares",
    "Resende Costa",
    "Rio Acima",
    "Rio do Prado",
    "Rio Novo",
    "Rio Paranaíba",
    "Salinas",
    "Santa Bárbara",
    "Santa Rita de Caldas",
    "Santa Rita do Sapucaí",
    "São João da Ponte",
    "São João Nepomuceno",
    "São José da Lapa",
    "São Pedro dos Ferros",
    "São Roque de Minas",
    "São Tiago",
    "Taiobeiras",
    "Turmalina",
    "Urucânia",
    "Vargem Grande do Rio Pardo",
    "Várzea da Palma",
    "Vazante",
    "Verdelândia",
    "Veredinha",
    "Virgínia",
    "Virginópolis",
  ],
  PA: [
    "Belém",
    "Ananindeua",
    "Santarém",
    "Marabá",
    "Parauapebas",
    "Castanhal",
    "Abaetetuba",
    "Cametá",
    "Marituba",
    "Altamira",
    "Tucuruí",
    "Bragança",
    "Paragominas",
    "Redenção",
    "Barcarena",
    "Benevides",
    "Capanema",
    "Tailândia",
    "Oriximiná",
    "Breves",
    "Salinópolis",
    "São Félix do Xingu",
    "Itaituba",
    "Vigia",
    "Santa Isabel do Pará",
    "Conceição do Araguaia",
    "Tomé-Açu",
    "Óbidos",
    "Moju",
    "Monte Alegre",
    "Igarapé-Miri",
    "Capitão Poço",
    "São Miguel do Guamá",
    "Acará",
    "Xinguara",
    "Juruti",
    "Inhangapi",
    "Dom Eliseu",
    "Ourilândia do Norte",
    "Mocajuba",
    "Goianésia do Pará",
    "Rondon do Pará",
    "Breu Branco",
    "Igarapé-Açu",
    "Novo Progresso",
    "São Domingos do Capim",
    "Aurora do Pará",
    "Ulianópolis",
    "Novo Repartimento",
    "Brasil Novo",
    "Soure",
    "Almeirim",
    "Medicilândia",
    "Placas",
    "Jacareacanga",
    "Rurópolis",
    "Porto de Moz",
    "Curralinho",
    "Quatipuru",
    "Garrafão do Norte",
    "Viseu",
    "São Caetano de Odivelas",
    "Ipixuna do Pará",
    "Curuá",
    "Portel",
    "Salvaterra",
    "Muaná",
    "Tracuateua",
    "Primavera",
    "Bannach",
    "Água Azul do Norte",
    "Rio Maria",
    "São Geraldo do Araguaia",
    "Floresta do Araguaia",
    "Eldorado dos Carajás",
    "Piçarra",
    "Palestina do Pará",
    "São João do Araguaia",
    "Cumaru do Norte",
    "Sapucaia",
    "Canaã dos Carajás",
    "Curionópolis",
  ],
  PB: [
    "João Pessoa",
    "Campina Grande",
    "Santa Rita",
    "Patos",
    "Bayeux",
    "Sousa",
    "Cajazeiras",
    "Cabedelo",
    "Guarabira",
    "Mamanguape",
    "Sapé",
    "Desterro",
    "Conde",
    "Monteiro",
    "Picuí",
    "Itabaiana",
    "Esperança",
    "Princesa Isabel",
    "São Bento",
    "Sumé",
    "Pombal",
    "Areia",
    "Queimadas",
    "Catolé do Rocha",
    "Alagoa Grande",
    "São João do Cariri",
    "Conceição",
    "Taperoá",
    "Solânea",
    "Bananeiras",
    "São José de Piranhas",
    "Itaporanga",
    "Cuité",
    "Ingá",
    "Mari",
    "Pedras de Fogo",
    "Alagoinha",
    "Lucena",
    "Pitimbu",
    "Coremas",
    "Piancó",
    "Brejo do Cruz",
    "Umbuzeiro",
    "Lagoa Seca",
    "Aroeiras",
    "Fagundes",
    "Massaranduba",
    "Riacho de Santo Antônio",
    "São José dos Cordeiros",
    "Campina Grande",
    "Água Branca",
    "Aguiar",
    "Alagoa Nova",
    "Alagoinha",
    "Alcantil",
    "Algodão de Jandaíra",
    "Alhandra",
    "São João do Tigre",
    "São José da Lagoa Tapada",
    "São José de Caiana",
    "São José de Espinharas",
    "São José do Bonfim",
    "São José do Brejo do Cruz",
    "São José do Sabugi",
    "São José dos Ramos",
    "São Mamede",
    "São Miguel de Taipu",
    "São Sebastião de Lagoa de Roça",
    "São Sebastião do Umbuzeiro",
    "Serra Branca",
    "Serra da Raiz",
    "Serra Grande",
    "Serra Redonda",
    "Serraria",
    "Sertãozinho",
    "Sobrado",
    "Sossêgo",
    "Tavares",
    "Teixeira",
    "Tenório",
    "Triunfo",
    "Uiraúna",
    "Várzea",
    "Vieirópolis",
    "Vista Serrana",
    "Zabelê",
  ],
  PR: [
    "Curitiba",
    "Londrina",
    "Maringá",
    "Ponta Grossa",
    "Cascavel",
    "São José dos Pinhais",
    "Foz do Iguaçu",
    "Colombo",
    "Guarapuava",
    "Paranaguá",
    "Araucária",
    "Toledo",
    "Apucarana",
    "Pinhais",
    "Campo Largo",
    "Arapongas",
    "Almirante Tamandaré",
    "Umuarama",
    "Piraquara",
    "Cambé",
    "Campo Mourão",
    "Fazenda Rio Grande",
    "Sarandi",
    "Fazenda Belém",
    "Paranavaí",
    "Francisco Beltrão",
    "Pato Branco",
    "Cianorte",
    "Telêmaco Borba",
    "Castro",
    "Rolândia",
    "Irati",
    "União da Vitória",
    "Ibiporã",
    "Prudentópolis",
    "Marechal Cândido Rondon",
    "Cornélio Procópio",
    "Dois Vizinhos",
    "São Mateus do Sul",
    "Palmas",
    "Bandeirantes",
    "Laranjeiras do Sul",
    "Matinhos",
    "Lapa",
    "Realeza",
    "Quedas do Iguaçu",
    "Boa Vista da Aparecida",
    "Medianeira",
    "São João do Ivaí",
    "Chopinzinho",
    "Pérola",
    "Coronel Vivida",
    "Assis Chateaubriand",
    "Santo Antônio da Platina",
    "Nova Esperança",
    "São José da Boa Vista",
    "Cerro Azul",
    "Wenceslau Braz",
    "Jaguariaíva",
    "Mandaguari",
    "Antonina",
    "Morretes",
    "Guaratuba",
    "Pontal do Paraná",
    "Loanda",
    "Terra Roxa",
    "Goioerê",
    "Palmeira",
    "Ivaiporã",
    "São Miguel do Iguaçu",
    "Matelândia",
    "Ampére",
    "Cruzeiro do Oeste",
    "Cândido de Abreu",
    "Reserva",
    "Ventania",
    "Tijucas do Sul",
    "Quitandinha",
    "Mandirituba",
    "Agudos do Sul",
    "Contenda",
    "Balsa Nova",
    "Rio Negro",
    "São José dos Pinhais",
    "Quatro Barras",
    "Campina Grande do Sul",
    "Bocaiúva do Sul",
    "Tunas do Paraná",
    "Adrianópolis",
    "Doutor Ulysses",
    "Itaperuçu",
    "Rio Branco do Sul",
  ],
  PE: [
    "Recife",
    "Jaboatão dos Guararapes",
    "Olinda",
    "Caruaru",
    "Petrolina",
    "Paulista",
    "Cabo de Santo Agostinho",
    "Camaragibe",
    "Garanhuns",
    "Vitória de Santo Antão",
    "Igarassu",
    "São Lourenço da Mata",
    "Santa Cruz do Capibaribe",
    "Abreu e Lima",
    "Ipojuca",
    "Serra Talhada",
    "Araripina",
    "Gravatá",
    "Carpina",
    "Goiana",
    "Belo Jardim",
    "Arcoverde",
    "Ouricuri",
    "Escada",
    "Pesqueira",
    "Surubim",
    "Palmares",
    "Bezerros",
    "Salgueiro",
    "São Bento do Una",
    "Buíque",
    "Limoeiro",
    "Paudalho",
    "Timbaúba",
    "São José do Egito",
    "Toritama",
    "Afogados da Ingazeira",
    "Ribeirão",
    "Rio Formoso",
    "Condado",
    "Águas Belas",
    "Floresta",
    "São José da Coroa Grande",
    "Nazaré da Mata",
    "São Vicente Ferrer",
    "Moreno",
    "Brejo da Madre de Deus",
    "Tabira",
    "São Caetano",
    "Glória do Goitá",
    "Macaparana",
    "Buenos Aires",
    "Feira Nova",
    "Aliança",
    "Itaquitinga",
    "São João",
    "Chã de Alegria",
    "Vicência",
    "Tracunhaém",
    "Machados",
    "Chã Grande",
    "Passira",
    "Sairé",
    "Cumaru",
    "Riacho das Almas",
    "Agrestina",
    "Altinho",
    "Cachoeirinha",
    "Casinhas",
    "Cupira",
    "Jataúba",
    "Jurema",
    "Panelas",
    "Pesqueira",
    "Poção",
    "Sanharó",
    "São Bento do Una",
    "Tacaimbó",
    "Venturosa",
    "Xexéu",
    "Angelim",
    "Calçado",
    "Canhotinho",
    "Correntes",
    "Águas Belas",
    "Iati",
    "Lajedo",
    "Palmeirina",
    "Paranatama",
    "Pedra",
    "Quipapá",
    "São João",
    "Terezinha",
    "Tupanatinga",
  ],
  PI: [
    "Teresina",
    "Parnaíba",
    "Picos",
    "Piripiri",
    "Floriano",
    "Campo Maior",
    "Barras",
    "União",
    "Altos",
    "Esperantina",
    "Pedro II",
    "Valença do Piauí",
    "São Raimundo Nonato",
    "Amarante",
    "Bom Jesus",
    "Corrente",
    "Uruçuí",
    "Oeiras",
    "Luzilândia",
    "Jaicós",
    "São João do Piauí",
    "Cocal",
    "Água Branca",
    "Simplício Mendes",
    "Castelo do Piauí",
    "José de Freitas",
    "Regeneração",
    "Miguel Alves",
    "Buriti dos Lopes",
    "Fronteiras",
    "Beneditinos",
    "Inhuma",
    "São José do Divino",
    "Cristalândia do Piauí",
    "Elesbão Veloso",
    "Hugo Napoleão",
    "Monsenhor Gil",
    "Nazaré do Piauí",
    "São Miguel do Tapuio",
    "Agricolândia",
    "Angical do Piauí",
    "Aroazes",
    "Arraial",
    "Assunção do Piauí",
    "Avelino Lopes",
    "Baixa Grande do Ribeiro",
    "Barra D'Alcântara",
    "Barreiras do Piauí",
    "Barro Duro",
    "Batalha",
    "Bela Vista do Piauí",
    "Belém do Piauí",
    "Bertolínia",
    "Betânia do Piauí",
    "Boa Hora",
    "Bocaina",
    "Boqueirão do Piauí",
    "Brasileira",
    "Brejo do Piauí",
    "Buriti dos Montes",
    "Cajazerias do Piauí",
    "Caldeirão Grande do Piauí",
    "Campinas do Piauí",
    "Campo Alegre do Fidalgo",
    "Campo Grande do Piauí",
    "Canavieira",
    "Canto do Buriti",
    "Capitão de Campos",
    "Capitão Gervásio Oliveira",
    "Caracol",
    "Caraúbas do Piauí",
    "Caridade do Piauí",
    "Castelo do Piauí",
    "Caxingó",
    "Cocal de Telha",
    "Cocal dos Alves",
    "Coivaras",
    "Colônia do Gurguéia",
    "Colônia do Piauí",
    "Conceição do Canindé",
    "Coronel José Dias",
    "Cristino Castro",
    "Curimatá",
    "Currais",
    "Curral Novo do Piauí",
    "Curralinhos",
    "Demerval Lobão",
    "Dirceu Arcoverde",
    "Dom Expedito Lopes",
    "Domingos Mourão",
    "Dom Inocêncio",
    "Eliseu Martins",
    "Esperantina",
    "Fartura do Piauí",
    "Flores do Piauí",
    "Floresta do Piauí",
    "Francinópolis",
    "Francisco Ayres",
    "Francisco Macedo",
    "Francisco Santos",
    "Geminiano",
    "Gilbués",
    "Guadalupe",
    "Guaribas",
    "Hugo Napoleão",
    "Ilha Grande",
    "Inspiração",
    "Ipiranga do Piauí",
    "Isaías Coelho",
    "Itainópolis",
    "Itaueira",
    "Jacobina do Piauí",
    "Jatobá do Piauí",
    "Jerumenha",
    "João Costa",
    "Joaquim Pires",
    "Joca Marques",
    "José de Freitas",
    "Juazeiro do Piauí",
    "Júlio Borges",
    "Jurema",
    "Lagoinha do Piauí",
    "Lagoa Alegre",
    "Lagoa do Barro do Piauí",
    "Lagoa de São Francisco",
    "Lagoa do Piauí",
    "Lagoa do Sítio",
    "Landri Sales",
    "Luís Correia",
    "Luzilândia",
    "Madeiro",
    "Manoel Emídio",
    "Marcolândia",
    "Marcos Parente",
    "Massapê do Piauí",
    "Matias Olímpio",
    "Milton Brandão",
    "Monte Alegre do Piauí",
    "Morro Cabeça no Tempo",
    "Morro do Chapéu do Piauí",
    "Murici dos Portelas",
    "Nazária",
    "Nossa Senhora de Nazaré",
    "Nossa Senhora dos Remédios",
    "Nova Santa Rita",
    "Novo Oriente do Piauí",
    "Novo Santo Antônio",
    "Oeiras",
    "Olho d'Água do Piauí",
    "Padre Marcos",
    "Paes Landim",
    "Pajeú do Piauí",
    "Palmeira do Piauí",
    "Palmeirais",
    "Paquetá",
    "Parnaguá",
    "Parnaíba",
    "Passagem Franca do Piauí",
    "Patos do Piauí",
    "Pau d'Arco do Piauí",
    "Paulistana",
    "Pavussu",
    "Pedro Laurentino",
    "Picos",
    "Pimenteiras",
    "Pio IX",
    "Piracuruca",
    "Piripiri",
    "Porto",
    "Porto Alegre do Piauí",
    "Prata do Piauí",
    "Queimada Nova",
    "Redenção do Gurguéia",
    "Regeneração",
    "Riacho Frio",
    "Ribeira do Piauí",
    "Ribeiro Gonçalves",
    "Rio Grande do Piauí",
    "Santa Cruz do Piauí",
    "Santa Cruz dos Milagres",
    "Santa Filomena",
    "Santa Luz",
    "Santa Rosa do Piauí",
    "Santo Antônio de Lisboa",
    "Santo Antônio dos Milagres",
    "Santo Inácio do Piauí",
    "São Braz do Piauí",
    "São Félix do Piauí",
    "São Francisco de Assis do Piauí",
    "São Francisco do Piauí",
    "São Gonçalo do Gurguéia",
    "São Gonçalo do Piauí",
    "São João da Canabrava",
    "São João da Fronteira",
    "São João da Serra",
    "São João da Varjota",
    "São João do Arraial",
    "São José do Peixe",
    "São José do Piauí",
    "São Julião",
    "São Lourenço do Piauí",
    "São Luis do Piauí",
    "São Miguel da Baixa Grande",
    "São Miguel do Fidalgo",
    "São Pedro do Piauí",
    "São Raimundo Nonato",
    "Sebastião Barros",
    "Sebastião Leal",
    "Sigefredo Pacheco",
    "Simões",
    "Simplício Mendes",
    "Socorro do Piauí",
    "Sussuapara",
    "Tamboril do Piauí",
    "Tanque do Piauí",
    "Teresina",
    "União",
    "Uruçuí",
    "Valença do Piauí",
    "Várzea Branca",
    "Várzea Grande",
    "Vera Mendes",
    "Vila Nova do Piauí",
    "Wall Ferraz",
  ],
  RJ: [
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Campos dos Goytacazes",
    "Belford Roxo",
    "São João de Meriti",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Macaé",
    "Itaboraí",
    "Cabo Frio",
    "Angra dos Reis",
    "Nova Friburgo",
    "Barra Mansa",
    "Teresópolis",
    "Mesquita",
    "Nilópolis",
    "Maricá",
    "Queimados",
    "Rio das Ostras",
    "Resende",
    "Araruama",
    "Itaguaí",
    "Japeri",
    "Itaperuna",
    "São Pedro da Aldeia",
    "Barra do Piraí",
    "Seropédica",
    "Saquarema",
    "Três Rios",
    "Valença",
    "Rio Bonito",
    "Guapimirim",
    "Cachoeiras de Macacu",
    "Paracambi",
    "Paraíba do Sul",
    "São Francisco de Itabapoana",
    "Itaocara",
    "Mangaratiba",
    "São Fidélis",
    "Rio Claro",
    "Casimiro de Abreu",
    "Silva Jardim",
    "São José do Vale do Rio Preto",
    "Conceição de Macabu",
    "Santa Maria Madalena",
    "Miracema",
    "Laje do Muriaé",
    "Cantagalo",
    "Cordeiro",
    "São Sebastião do Alto",
    "Carmo",
    "Sumidouro",
    "Duas Barras",
    "Bom Jardim",
    "Trajano de Moraes",
    "Macuco",
    "Cambuci",
    "São José de Ubá",
    "Aperibé",
    "Santo Antônio de Pádua",
    "Italva",
    "Varre-Sai",
    "Natividade",
    "Porciúncula",
    "Bom Jesus do Itabapoana",
    "Itaocara",
    "Carapebus",
    "Quissamã",
    "Armação dos Búzios",
    "Arraial do Cabo",
    "São João da Barra",
    "Cardoso Moreira",
    "Italva",
    "Tanguá",
    "Rio de Janeiro",
    "Engenheiro Paulo de Frontin",
    "Miguel Pereira",
    "Paty do Alferes",
    "Vassouras",
    "Mendes",
    "Paulo de Frontin",
    "Sapucaia",
    "Pinheiral",
    "Porto Real",
    "Quatis",
    "Itatiaia",
    "Penedo",
    "Visconde de Mauá",
  ],
  RN: [
    "Natal",
    "Mossoró",
    "Parnamirim",
    "São Gonçalo do Amarante",
    "Macaíba",
    "Ceará-Mirim",
    "Caicó",
    "Assú",
    "Currais Novos",
    "Nova Cruz",
    "São José de Mipibu",
    "Santa Cruz",
    "João Câmara",
    "Canguaretama",
    "Touros",
    "Extremoz",
    "Nísia Floresta",
    "São Paulo do Potengi",
    "Monte Alegre",
    "Goianinha",
    "Pedro Velho",
    "Tibau do Sul",
    "Senador Georgino Avelino",
    "Baía Formosa",
    "Espírito Santo",
    "Vila Flor",
    "Tangará",
    "São Bento do Norte",
    "Pendências",
    "Carnaubais",
    "Areia Branca",
    "Grossos",
    "Tibau",
    "Caraúbas",
    "Governador Dix-Sept Rosado",
    "Upanema",
    "Felipe Guerra",
    "Janduís",
    "Alexandria",
    "Pau dos Ferros",
    "José da Penha",
    "Riacho da Cruz",
    "Encanto",
    "Martins",
    "Portalegre",
    "Venha-Ver",
    "Francisco Dantas",
    "Serrinha dos Pintos",
    "São Miguel",
    "Coronel João Pessoa",
    "Doutor Severiano",
    "Riacho de Santana",
    "Rodolfo Fernandes",
    "Umarizal",
    "Lucrécia",
    "Antônio Martins",
    "Frutuoso Gomes",
    "Olho-d'Água do Borges",
    "Patu",
    "Messias Targino",
    "Paraná",
    "Almino Afonso",
    "São Francisco do Oeste",
    "Itaú",
    "Apodi",
    "Severiano Melo",
    "Caraúbas",
    "Campo Grande",
    "Janduís",
    "Messias Targino",
    "Triunfo Potiguar",
    "Viçosa",
    "Ipanguaçu",
    "Carnaubais",
    "Jandaíra",
    "Pedra Preta",
    "São Rafael",
    "Angicos",
    "Fernando Pedroza",
    "Pedro Avelino",
    "Lajes",
    "Jardim de Angicos",
    "Afonso Bezerra",
    "Jucurutu",
    "São José do Seridó",
    "Jardim do Seridó",
    "Parelhas",
    "Equador",
    "Santana do Seridó",
    "Cerro Corá",
    "Lagoa Nova",
    "Florânia",
    "Cruzeta",
    "Acari",
    "Currais Novos",
    "Carnaúba dos Dantas",
    "São João do Sabugi",
    "Ouro Branco",
    "São Vicente",
    "Timbaúba dos Batistas",
    "São Fernando",
    "Bodó",
    "Tenente Laurentino Cruz",
    "São José do Campestre",
    "Ruy Barbosa",
    "Barcelona",
    "Caiçara do Rio do Vento",
    "São Tomé",
    "Lajes Pintadas",
    "Bento Fernandes",
    "Jandaíra",
    "Pureza",
    "Taipu",
    "Poço Branco",
    "São Pedro",
    "Bom Jesus",
    "Senador Elói de Souza",
    "Ielmo Marinho",
    "Várzea",
    "Vera Cruz",
    "Passa e Fica",
    "Santa Maria",
    "Lagoa d'Anta",
    "Montanhas",
    "Jaçanã",
    "Japi",
    "Riachuelo",
    "Riacho de Santana",
    "Campo Redondo",
    "Coronel Ezequiel",
    "Sítio Novo",
    "Lagoa de Velhos",
    "Lagoa Salgada",
    "São José do Mipibu",
    "Monte das Gameleiras",
    "Usina",
  ],
  RS: [
    "Porto Alegre",
    "Caxias do Sul",
    "Pelotas",
    "Canoas",
    "Santa Maria",
    "Gravataí",
    "Viamão",
    "Novo Hamburgo",
    "São Leopoldo",
    "Rio Grande",
    "Alvorada",
    "Passo Fundo",
    "Sapucaia do Sul",
    "Uruguaiana",
    "Santa Cruz do Sul",
    "Cachoeirinha",
    "Bagé",
    "Bento Gonçalves",
    "Erechim",
    "Guaíba",
    "Santana do Livramento",
    "Esteio",
    "Ijuí",
    "Alegrete",
    "Pelotas",
    "Lajeado",
    "Sapiranga",
    "São Borja",
    "Cachoeira do Sul",
    "Camaquã",
    "Venâncio Aires",
    "São Gabriel",
    "Cruz Alta",
    "Montenegro",
    "São Jerônimo",
    "Carazinho",
    "Eldorado do Sul",
    "Santo Ângelo",
    "Dom Pedrito",
    "Santiago",
    "Parobé",
    "Taquara",
    "Charqueadas",
    "Farroupilha",
    "Carlos Barbosa",
    "Garibaldi",
    "Marau",
    "Tramandaí",
    "Osório",
    "Capão da Canoa",
    "Torres",
    "Imbé",
    "Cidreira",
    "Palmares do Sul",
    "Mostardas",
    "Tavares",
    "São José do Norte",
    "Santa Vitória do Palmar",
    "Chuí",
    "Jaguarão",
    "Arroio Grande",
    "Herval",
    "Pedras Altas",
    "Pinheiro Machado",
    "Piratini",
    "Cerrito",
    "Pedro Osório",
    "Turuçu",
    "Morro Redondo",
    "Capão do Leão",
    "Rio Grande",
    "São Lourenço do Sul",
    "Cristal",
    "Canguçu",
    "São José do Sul",
    "Arambaré",
    "Tapes",
    "Camaquã",
    "Barra do Ribeiro",
    "Sertão Santana",
    "General Câmara",
    "Dom Feliciano",
    "Butiá",
    "Minas do Leão",
    "São Jerônimo",
    "Barão do Triunfo",
    "Arroio dos Ratos",
    "Pantano Grande",
    "Encruzilhada do Sul",
    "Amaral Ferrador",
    "Santana da Boa Vista",
    "Caçapava do Sul",
    "Bagé",
    "Hulha Negra",
    "Candiota",
    "Aceguá",
    "Dom Pedrito",
    "Lavras do Sul",
    "São Gabriel",
    "Rosário do Sul",
    "Santa Margarida do Sul",
    "Alegrete",
    "Manoel Viana",
    "São Francisco de Assis",
    "Jaguari",
    "Nova Esperança do Sul",
    "Unistalda",
    "Maçambará",
    "São Borja",
    "Itaqui",
    "Uruguaiana",
    "Barra do Quaraí",
    "Quaraí",
    "Santana do Livramento",
    "Rivera",
    "Dom Pedrito",
    "Hulha Negra",
  ],
  RO: [
    "Porto Velho",
    "Ji-Paraná",
    "Ariquemes",
    "Vilhena",
    "Cacoal",
    "Rolim de Moura",
    "Guajará-Mirim",
    "Jaru",
    "Ouro Preto do Oeste",
    "Machadinho d'Oeste",
    "Colorado do Oeste",
    "Cerejeiras",
    "Espigão d'Oeste",
    "Pimenta Bueno",
    "Buritis",
    "São Miguel do Guaporé",
    "Nova Brasilândia d'Oeste",
    "Presidente Médici",
    "Costa Marques",
    "São Francisco do Guaporé",
    "Alta Floresta d'Oeste",
    "Santa Luzia d'Oeste",
    "Novo Horizonte do Oeste",
    "Ministro Andreazza",
    "Alvorada d'Oeste",
    "Urupá",
    "Vale do Anari",
    "Nova Mamoré",
    "Campo Novo de Rondônia",
    "Candeias do Jamari",
    "Itapuã do Oeste",
    "Cacaulândia",
    "Monte Negro",
    "Rio Crespo",
    "Cujubim",
    "Governador Jorge Teixeira",
    "Mirante da Serra",
    "Nova União",
    "Teixeirópolis",
    "Vale do Paraíso",
    "Theobroma",
    "Parecis",
    "Chupinguaia",
    "Corumbiara",
    "Pimenteiras do Oeste",
    "Primavera de Rondônia",
    "São Felipe d'Oeste",
    "Seringueiras",
  ],
  RR: [
    "Boa Vista",
    "Rorainópolis",
    "Caracaraí",
    "Alto Alegre",
    "Mucajaí",
    "Cantá",
    "Bonfim",
    "Normandia",
    "Caroebe",
    "São João da Baliza",
    "São Luiz",
    "Iracema",
    "Amajari",
    "Pacaraima",
    "Uiramutã",
  ],
  SC: [
    "Florianópolis",
    "Joinville",
    "Blumenau",
    "São José",
    "Criciúma",
    "Chapecó",
    "Itajaí",
    "Lages",
    "Jaraguá do Sul",
    "Palhoça",
    "Balneário Camboriú",
    "Biguaçu",
    "Tubarão",
    "São Bento do Sul",
    "Caçador",
    "Camboriú",
    "Navegantes",
    "Concórdia",
    "Rio do Sul",
    "Araranguá",
    "Gaspar",
    "Brusque",
    "Canoinhas",
    "Içara",
    "Videira",
    "Araquari",
    "Indaial",
    "Criciumal",
    "Imbituba",
    "São Francisco do Sul",
    "Xanxerê",
    "Balneário Piçarras",
    "Santo Amaro da Imperatriz",
    "Pomerode",
    "São Miguel do Oeste",
    "Curitibanos",
    "Tijucas",
    "Itapema",
    "Mafra",
    "Braço do Norte",
    "Porto Belo",
    "Bombinhas",
    "Governador Celso Ramos",
    "São Pedro de Alcântara",
    "Paulo Lopes",
    "Águas Mornas",
    "Antonio Carlos",
    "Angelina",
    "Major Gercino",
    "Rancho Queimado",
    "Anitápolis",
    "São Bonifácio",
    "Águas Mornas",
    "Alfredo Wagner",
    "Leoberto Leal",
    "Águas Mornas",
    "São Martinho",
    "Bocaina do Sul",
    "Urubici",
    "Urupema",
    "Bom Jardim da Serra",
    "Orleans",
    "Grão Pará",
    "São Ludgero",
    "Braço do Trombudo",
    "Agrolândia",
    "Trombudo Central",
    "Ibirama",
    "Lontras",
    "Apiúna",
    "Ascurra",
    "Benedito Novo",
    "Doutor Pedrinho",
    "Rodeio",
    "Timbó",
    "Rio dos Cedros",
    "Presidente Getúlio",
    "José Boiteux",
    "Vitor Meireles",
    "Witmarsum",
    "Presidente Nereu",
    "Ibirama",
    "Chapadão do Lageado",
    "Petrolândia",
    "Salete",
    "Taió",
    "Mirim Doce",
    "Ituporanga",
    "Imbuia",
    "Atalanta",
    "Aurora",
    "Braço do Trombudo",
    "Dona Emma",
    "Ibirama",
    "Laurentino",
    "Lontras",
    "Pouso Redondo",
    "Rio do Campo",
    "Rio do Oeste",
    "Taió",
    "Trombudo Central",
    "Vidal Ramos",
    "Witmarsum",
    "Agronômica",
    "Benedito Novo",
    "Blumenau",
    "Botuverá",
    "Brusque",
    "Canelinha",
    "Doutor Pedrinho",
    "Gaspar",
    "Guabiruba",
    "Ilhota",
    "Indaial",
    "Luiz Alves",
    "Massaranduba",
    "Nova Trento",
    "Pomerode",
    "Rio dos Cedros",
    "Rodeio",
    "São João Batista",
    "Timbó",
  ],
  SP: [
    "São Paulo",
    "Guarulhos",
    "Campinas",
    "São Bernardo do Campo",
    "Santo André",
    "Osasco",
    "Ribeirão Preto",
    "Sorocaba",
    "Santos",
    "São José dos Campos",
    "Mauá",
    "São Vicente",
    "Piracicaba",
    "Carapicuíba",
    "Bauru",
    "Jundiaí",
    "Franca",
    "São Carlos",
    "Praia Grande",
    "Limeira",
    "Suzano",
    "Taboão da Serra",
    "Diadema",
    "Embu das Artes",
    "Indaiatuba",
    "Cotia",
    "Americana",
    "Araraquara",
    "Jacareí",
    "Presidente Prudente",
    "Hortolândia",
    "Rio Claro",
    "Marília",
    "Taubaté",
    "Araçatuba",
    "Guarujá",
    "Itaquaquecetuba",
    "Francisco Morato",
    "Itu",
    "Bragança Paulista",
    "Pindamonhangaba",
    "São Caetano do Sul",
    "Ferraz de Vasconcelos",
    "Salto",
    "Ourinhos",
    "Botucatu",
    "Catanduva",
    "Assis",
    "Barretos",
    "Guaratinguetá",
    "Leme",
    "Valinhos",
    "Vinhedo",
    "Jales",
    "São João da Boa Vista",
    "Avaré",
    "Atibaia",
    "Caraguatatuba",
    "Mococa",
    "Jaú",
    "Lins",
    "Monte Alto",
    "Tupã",
    "São Sebastião",
    "Adamantina",
    "Bebedouro",
    "Registro",
    "Cruzeiro",
    "Votuporanga",
    "São José do Rio Preto",
    "Fernandópolis",
    "Orlândia",
    "Santa Bárbara d'Oeste",
    "Nova Odessa",
    "Sumaré",
    "Paulínia",
    "Monte Mor",
    "Holambra",
    "Cosmópolis",
    "Artur Nogueira",
    "Engenheiro Coelho",
    "Jaguariúna",
    "Pedreira",
    "Conchal",
    "Mogi Mirim",
    "Itapira",
    "Águas de Lindóia",
    "Lindóia",
    "Serra Negra",
    "Socorro",
    "Mogi das Cruzes",
    "Itapevi",
    "Franco da Rocha",
    "Cajamar",
    "Itapecerica da Serra",
    "Embu-Guaçu",
    "Vargem Grande Paulista",
    "Jandira",
    "Barueri",
    "Santana de Parnaíba",
    "Caieiras",
    "Mairiporã",
    "Francisco Morato",
    "Franco da Rocha",
    "Cajamar",
    "Jordanésia",
    "Várzea Paulista",
    "Campo Limpo Paulista",
    "Jarinu",
    "Louveira",
    "Itatiba",
    "Morungaba",
    "Tuiuti",
    "Cabreúva",
    "Itu",
    "Salto",
    "Elias Fausto",
    "Monte Mor",
    "Capivari",
    "Rafard",
    "Mombuca",
    "Tietê",
    "Cerquilho",
    "Jumirim",
    "Laranjal Paulista",
    "Porangaba",
    "Quadra",
    "Tatuí",
    "Boituva",
    "Pereiras",
    "Anhembi",
    "Bofete",
    "Conchas",
    "Areiópolis",
    "Itatinga",
    "Pardinho",
    "Botucatu",
    "São Manuel",
    "Pratânia",
    "Avaré",
    "Cerqueira César",
    "Manduri",
    "Óleo",
    "Bernardino de Campos",
    "Santa Bárbara d'Oeste",
    "Nova Odessa",
    "Americana",
    "Santa Barbara d'Oeste",
    "Limeira",
    "Iracemápolis",
    "Cordeirópolis",
    "Santa Gertrudes",
    "Rio das Pedras",
    "Charqueada",
    "São Pedro",
    "Águas de São Pedro",
    "Brotas",
    "Torrinha",
    "Dois Córregos",
    "Mineiros do Tietê",
    "Barra Bonita",
    "Igaraçu do Tietê",
    "Macatuba",
    "Lençóis Paulista",
    "Arealva",
    "Pederneiras",
    "Agudos",
    "Piratininga",
    "Cabrália Paulista",
    "Avaí",
    "Reginópolis",
    "Itaju",
    "Bocaina",
    "Arealva",
    "Sabino",
    "Presidente Alves",
    "Guarantã",
    "Getulina",
    "Guaiçara",
    "Lins",
    "Promissão",
    "Avanhandava",
    "Barbosa",
    "Pirajuí",
    "Cafelândia",
    "Pongaí",
    "Uru",
    "Duartina",
    "Gália",
    "Garça",
    "Alvinlândia",
    "Lupércio",
    "Marília",
    "Vera Cruz",
    "Oriente",
    "Echaporã",
    "Ocauçu",
    "Pompéia",
    "Quintana",
    "Borá",
    "Júlio Mesquita",
    "Fernão",
    "Arco-Íris",
    "Tupã",
    "Iacri",
    "Parapuã",
    "Bastos",
    "Queiroz",
    "Herculândia",
    "Álvaro de Carvalho",
    "Alvinlândia",
    "Campos Novos Paulista",
    "Echaporã",
    "Fernão",
    "Gália",
    "Garça",
    "Herculândia",
    "Iacri",
    "Lupércio",
    "Marília",
    "Ocauçu",
    "Oriente",
    "Oscar Bressane",
    "Pompéia",
    "Queiroz",
    "Quintana",
    "Vera Cruz",
  ],
  SE: [
    "Aracaju",
    "Nossa Senhora do Socorro",
    "Lagarto",
    "Itabaiana",
    "Estância",
    "Tobias Barreto",
    "Simão Dias",
    "Propriá",
    "São Cristóvão",
    "Barra dos Coqueiros",
    "Carmópolis",
    "Ribeirópolis",
    "Aquidabã",
    "Capela",
    "Laranjeiras",
    "Maruim",
    "Rosário do Catete",
    "Riachuelo",
    "Santa Rosa de Lima",
    "Santo Amaro das Brotas",
    "Divina Pastora",
    "Siriri",
    "General Maynard",
    "Pacatuba",
    "Pirambu",
    "Japaratuba",
    "Japoatã",
    "Neópolis",
    "Santana do São Francisco",
    "Canhoba",
    "Ilha das Flores",
    "Brejo Grande",
    "Pacatuba",
    "Telha",
    "Amparo de São Francisco",
    "Cedro de São João",
    "Malhada dos Bois",
    "Muribeca",
    "Nossa Senhora das Dores",
    "Riachão do Dantas",
    "Tomar do Geru",
    "Cristinápolis",
    "Indiaroba",
    "Itabaianinha",
    "Pedrinhas",
    "Umbaúba",
    "Arauá",
    "Boquim",
    "Pedra Mole",
    "Salgado",
    "Santa Luzia do Itanhy",
    "Macambira",
    "Moita Bonita",
    "São Domingos",
    "Campo do Brito",
    "Carira",
    "Frei Paulo",
    "Pinhão",
    "Nossa Senhora Aparecida",
    "São Miguel do Aleixo",
    "Feira Nova",
    "Nossa Senhora da Glória",
    "Poço Verde",
    "Monte Alegre de Sergipe",
    "Porto da Folha",
    "Gararu",
    "Itabi",
    "Nossa Senhora de Lourdes",
    "Canindé de São Francisco",
    "Poço Redondo",
  ],
  TO: [
    "Palmas",
    "Araguaína",
    "Gurupi",
    "Porto Nacional",
    "Paraíso do Tocantins",
    "Colinas do Tocantins",
    "Guaraí",
    "Tocantinópolis",
    "Miracema do Tocantins",
    "Formoso do Araguaia",
    "Dianópolis",
    "Taguatinga",
    "Pedro Afonso",
    "Xambioá",
    "Arraias",
    "Augustinópolis",
    "Couto Magalhães",
    "Filadélfia",
    "Pium",
    "Ananás",
    "Araguatins",
    "Axixá do Tocantins",
    "Babaçulândia",
    "Buriti do Tocantins",
    "Carmolândia",
    "Carrasco Bonito",
    "Caseara",
    "Centenário",
    "Combinado",
    "Conceição do Tocantins",
    "Cristalândia",
    "Darcinópolis",
    "Esperantina",
    "Fátima",
    "Figueirópolis",
    "Goianorte",
    "Goiatins",
    "Itacajá",
    "Itaguatins",
    "Itapiratins",
    "Lizarda",
    "Luzinópolis",
    "Maurilândia do Tocantins",
    "Nazaré",
    "Nova Olinda",
    "Oliveira de Fátima",
    "Pau D'Arco",
    "Praia Norte",
    "Riachinho",
    "Sampaio",
    "Santa Fé do Araguaia",
    "Santa Maria do Tocantins",
    "São Bento do Tocantins",
    "São Miguel do Tocantins",
    "São Sebastião do Tocantins",
    "Sítio Novo do Tocantins",
    "Wanderlândia",
    "Almas",
    "Alvorada",
    "Angico",
    "Aurora do Tocantins",
    "Baianópolis",
    "Barra do Ouro",
    "Campos Lindos",
    "Chapada da Natividade",
    "Conceição do Tocantins",
    "Dianópolis",
    "Dois Irmãos do Tocantins",
    "Lavandeira",
    "Mateiros",
    "Monte do Carmo",
    "Natividade",
    "Novo Acordo",
    "Novo Jardim",
    "Pindorama do Tocantins",
    "Ponte Alta do Bom Jesus",
    "Ponte Alta do Tocantins",
    "Porto Alegre do Tocantins",
    "Recursolândia",
    "Rio da Conceição",
    "Rio Sono",
    "Santa Rosa do Tocantins",
    "Santa Tereza do Tocantins",
    "Santa Terezinha do Tocantins",
    "São Félix do Tocantins",
    "Silvanópolis",
    "Taipas do Tocantins",
    "Tupirama",
    "Tupiratins",
    "Aparecida do Rio Negro",
    "Araguacema",
    "Araguanã",
    "Barrolândia",
    "Brejinho de Nazaré",
    "Chapada de Areia",
    "Couto Magalhães",
    "Cristalândia",
    "Divinópolis do Tocantins",
    "Dois Irmãos do Tocantins",
    "Fortaleza do Tabocão",
    "Goianorte",
    "Itapiratins",
    "Juarina",
    "Lajeado",
    "Marianópolis do Tocantins",
    "Nova Rosalândia",
    "Pequizeiro",
    "Presidente Kennedy",
    "Sandolândia",
    "Santa Rita do Tocantins",
    "São Salvador do Tocantins",
  ],
};

export const getCitiesByState = (stateId: string): string[] => {
  if (!stateId || stateId.trim() === "") {
    return [];
  }

  const cities = brazilCities[stateId.toUpperCase()];
  console.log(
    `Getting cities for state: ${stateId}, found: ${cities?.length || 0} cities`,
  );

  return cities ? [...cities].sort() : [];
};
