-- Query para popular indicadores padrões com dados médicos abrangentes
-- Baseado no metapadrão implementado com todas as informações de metadados

INSERT INTO indicators (
  name, 
  description, 
  unit, 
  category, 
  subcategory, 
  context, 
  data_type, 
  definition, 
  is_required, 
  is_conditional, 
  is_repeatable, 
  standard_id, 
  source, 
  is_standard
) VALUES 

-- SINAIS VITAIS
('Pressão Arterial Sistólica', 
 'Pressão exercida pelo sangue contra as paredes das artérias durante a contração do ventrículo esquerdo', 
 'mmHg', 
 'Sinais Vitais', 
 'Pressão Arterial', 
 'Clinical', 
 'number', 
 'Medida da pressão máxima exercida pelo sangue nas artérias durante o ciclo cardíaco, correspondente à fase de sístole ventricular', 
 true, 
 false, 
 true, 
 'LOINC:8480-6', 
 'Organização Mundial da Saúde - Guidelines for Blood Pressure Measurement', 
 true),

('Pressão Arterial Diastólica', 
 'Pressão exercida pelo sangue contra as paredes das artérias durante o relaxamento do ventrículo esquerdo', 
 'mmHg', 
 'Sinais Vitais', 
 'Pressão Arterial', 
 'Clinical', 
 'number', 
 'Medida da pressão mínima exercida pelo sangue nas artérias durante o ciclo cardíaco, correspondente à fase de diástole ventricular', 
 true, 
 false, 
 true, 
 'LOINC:8462-4', 
 'Organização Mundial da Saúde - Guidelines for Blood Pressure Measurement', 
 true),

('Frequência Cardíaca', 
 'Número de batimentos cardíacos por minuto em repouso ou atividade', 
 'bpm', 
 'Sinais Vitais', 
 'Cardiovascular', 
 'Clinical', 
 'number', 
 'Frequência de contrações do músculo cardíaco por unidade de tempo, geralmente expressa em batimentos por minuto', 
 true, 
 false, 
 true, 
 'LOINC:8867-4', 
 'American Heart Association - Heart Rate Guidelines', 
 true),

('Temperatura Corporal', 
 'Temperatura central do corpo humano medida em diferentes locais anatômicos', 
 '°C', 
 'Sinais Vitais', 
 'Termorregulação', 
 'Clinical', 
 'number', 
 'Medida do grau de calor do corpo humano, indicativa do equilíbrio entre produção e perda de calor corporal', 
 true, 
 false, 
 true, 
 'LOINC:8310-5', 
 'International Federation of Clinical Chemistry - Temperature Standards', 
 true),

('Frequência Respiratória', 
 'Número de ciclos respiratórios (inspiração e expiração) por minuto', 
 'irpm', 
 'Sinais Vitais', 
 'Respiratório', 
 'Clinical', 
 'number', 
 'Frequência dos movimentos respiratórios por unidade de tempo, incluindo inspiração e expiração completas', 
 true, 
 false, 
 true, 
 'LOINC:9279-1', 
 'European Respiratory Society - Respiratory Rate Guidelines', 
 true),

('Saturação de Oxigênio', 
 'Percentual de hemoglobina saturada com oxigênio no sangue arterial', 
 '%', 
 'Sinais Vitais', 
 'Respiratório', 
 'Clinical', 
 'number', 
 'Medida da porcentagem de hemoglobina ligada ao oxigênio em relação à hemoglobina total no sangue', 
 true, 
 false, 
 true, 
 'LOINC:2708-6', 
 'World Health Organization - Pulse Oximetry Training Manual', 
 true),

-- MEDIDAS ANTROPOMÉTRICAS
('Peso Corporal', 
 'Massa corporal total do indivíduo medida em quilogramas', 
 'kg', 
 'Antropometria', 
 'Composição Corporal', 
 'Clinical', 
 'number', 
 'Medida da força gravitacional exercida sobre a massa total do corpo humano', 
 true, 
 false, 
 true, 
 'LOINC:29463-7', 
 'Organização Mundial da Saúde - Physical Status Assessment', 
 true),

('Altura', 
 'Distância vertical entre a base dos pés e o topo da cabeça em posição ereta', 
 'cm', 
 'Antropometria', 
 'Medidas Lineares', 
 'Clinical', 
 'number', 
 'Medida linear da estatura corporal total em posição anatômica padronizada', 
 true, 
 false, 
 false, 
 'LOINC:8302-2', 
 'International Society for the Advancement of Kinanthropometry', 
 true),

('Índice de Massa Corporal', 
 'Relação entre peso e altura ao quadrado, indicador de composição corporal', 
 'kg/m²', 
 'Antropometria', 
 'Composição Corporal', 
 'Clinical', 
 'number', 
 'Índice calculado pela divisão do peso corporal pelo quadrado da altura, utilizado para classificação do estado nutricional', 
 false, 
 true, 
 true, 
 'LOINC:39156-5', 
 'Organização Mundial da Saúde - BMI Classification Standards', 
 true),

('Circunferência Abdominal', 
 'Medida do perímetro abdominal na região de menor circunferência do tronco', 
 'cm', 
 'Antropometria', 
 'Medidas Circunferenciais', 
 'Clinical', 
 'number', 
 'Medida do perímetro da região abdominal, indicativa de distribuição de gordura corporal central', 
 false, 
 false, 
 true, 
 'LOINC:33747-0', 
 'International Diabetes Federation - Waist Circumference Guidelines', 
 true),

-- EXAMES LABORATORIAIS - HEMATOLOGIA
('Hemoglobina', 
 'Concentração da proteína transportadora de oxigênio nos eritrócitos', 
 'g/dL', 
 'Laboratório', 
 'Hematologia', 
 'Clinical', 
 'number', 
 'Concentração da metaloproteína rica em ferro presente nos glóbulos vermelhos, responsável pelo transporte de oxigênio', 
 true, 
 false, 
 true, 
 'LOINC:718-7', 
 'International Council for Standardization in Haematology', 
 true),

('Hematócrito', 
 'Percentual do volume sanguíneo ocupado pelos eritrócitos', 
 '%', 
 'Laboratório', 
 'Hematologia', 
 'Clinical', 
 'number', 
 'Proporção volumétrica de células vermelhas em relação ao volume total de sangue', 
 true, 
 false, 
 true, 
 'LOINC:4544-3', 
 'Clinical and Laboratory Standards Institute', 
 true),

('Contagem de Leucócitos', 
 'Número total de glóbulos brancos por unidade de volume sanguíneo', 
 'células/μL', 
 'Laboratório', 
 'Hematologia', 
 'Clinical', 
 'number', 
 'Quantificação das células de defesa do organismo presentes no sangue periférico', 
 true, 
 false, 
 true, 
 'LOINC:6690-2', 
 'International Society of Laboratory Hematology', 
 true),

('Contagem de Plaquetas', 
 'Número de trombócitos por unidade de volume sanguíneo', 
 'células/μL', 
 'Laboratório', 
 'Hematologia', 
 'Clinical', 
 'number', 
 'Quantificação das células responsáveis pela coagulação sanguínea no sangue periférico', 
 true, 
 false, 
 true, 
 'LOINC:777-3', 
 'International Society on Thrombosis and Haemostasis', 
 true),

-- EXAMES LABORATORIAIS - BIOQUÍMICA
('Glicemia de Jejum', 
 'Concentração de glicose no sangue após período de jejum de 8-12 horas', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida da concentração de açúcar no sangue em estado de jejum, indicativo do metabolismo glicídico', 
 true, 
 false, 
 true, 
 'LOINC:1558-6', 
 'American Diabetes Association - Standards of Medical Care', 
 true),

('Hemoglobina Glicada', 
 'Percentual de hemoglobina ligada irreversivelmente à glicose', 
 '%', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida do controle glicêmico médio dos últimos 2-3 meses através da glicação da hemoglobina', 
 false, 
 true, 
 true, 
 'LOINC:4548-4', 
 'International Federation of Clinical Chemistry - HbA1c Standardization', 
 true),

('Colesterol Total', 
 'Concentração total de colesterol no sangue incluindo todas as frações', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida da concentração total do esterol presente no plasma sanguíneo, indicativo do perfil lipídico', 
 true, 
 false, 
 true, 
 'LOINC:2093-3', 
 'National Cholesterol Education Program Guidelines', 
 true),

('HDL Colesterol', 
 'Concentração de colesterol ligado à lipoproteína de alta densidade', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida do colesterol transportado por lipoproteínas de alta densidade, considerado protetor cardiovascular', 
 true, 
 false, 
 true, 
 'LOINC:2085-9', 
 'European Society of Cardiology - Dyslipidemia Guidelines', 
 true),

('LDL Colesterol', 
 'Concentração de colesterol ligado à lipoproteína de baixa densidade', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida do colesterol transportado por lipoproteínas de baixa densidade, associado ao risco cardiovascular', 
 true, 
 false, 
 true, 
 'LOINC:18262-6', 
 'American Heart Association - Cholesterol Management Guidelines', 
 true),

('Triglicerídeos', 
 'Concentração de triglicerídeos no sangue em jejum', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida da concentração de lipídeos simples no plasma, indicativo do metabolismo lipídico', 
 true, 
 false, 
 true, 
 'LOINC:2571-8', 
 'International Atherosclerosis Society - Triglyceride Guidelines', 
 true),

('Creatinina Sérica', 
 'Concentração de creatinina no soro sanguíneo, indicador da função renal', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida do produto de degradação da creatina muscular, utilizada para avaliação da função renal', 
 true, 
 false, 
 true, 
 'LOINC:2160-0', 
 'Kidney Disease Improving Global Outcomes - Clinical Practice Guidelines', 
 true),

('Ureia', 
 'Concentração de ureia no sangue, produto final do metabolismo proteico', 
 'mg/dL', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida do principal produto nitrogenado da degradação de proteínas, indicativo da função renal', 
 true, 
 false, 
 true, 
 'LOINC:3094-0', 
 'National Kidney Foundation - Clinical Practice Guidelines', 
 true),

-- FUNÇÃO HEPÁTICA
('ALT/TGP', 
 'Concentração da enzima alanina aminotransferase no soro', 
 'U/L', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida da atividade enzimática hepática, indicativa de lesão ou disfunção dos hepatócitos', 
 true, 
 false, 
 true, 
 'LOINC:1742-6', 
 'American Association for the Study of Liver Diseases', 
 true),

('AST/TGO', 
 'Concentração da enzima aspartato aminotransferase no soro', 
 'U/L', 
 'Laboratório', 
 'Bioquímica', 
 'Clinical', 
 'number', 
 'Medida da atividade enzimática presente no fígado, coração e músculos, indicativa de lesão tecidual', 
 true, 
 false, 
 true, 
 'LOINC:1920-8', 
 'European Association for the Study of the Liver Guidelines', 
 true),

-- HORMÔNIOS E ENDOCRINOLOGIA
('TSH', 
 'Concentração do hormônio estimulante da tireoide no soro', 
 'mUI/L', 
 'Laboratório', 
 'Endocrinologia', 
 'Clinical', 
 'number', 
 'Medida do hormônio hipofisário que regula a função tireoidiana, indicativo do eixo hipotálamo-hipófise-tireoide', 
 true, 
 false, 
 true, 
 'LOINC:3016-3', 
 'American Thyroid Association - Management Guidelines', 
 true),

('T4 Livre', 
 'Concentração da fração livre do hormônio tiroxina no soro', 
 'ng/dL', 
 'Laboratório', 
 'Endocrinologia', 
 'Clinical', 
 'number', 
 'Medida da forma biologicamente ativa do principal hormônio tireoidiano, indicativa da função tireoidiana', 
 false, 
 true, 
 true, 
 'LOINC:3024-7', 
 'Endocrine Society - Thyroid Function Testing Guidelines', 
 true),

-- VITAMINAS E MINERAIS
('Vitamina D', 
 'Concentração de 25-hidroxivitamina D no soro', 
 'ng/mL', 
 'Laboratório', 
 'Vitaminas', 
 'Clinical', 
 'number', 
 'Medida da forma de armazenamento da vitamina D, indicativa do status vitamínico e metabolismo ósseo', 
 false, 
 false, 
 true, 
 'LOINC:1751-7', 
 'Endocrine Society - Vitamin D Clinical Practice Guidelines', 
 true),

('Vitamina B12', 
 'Concentração de cobalamina no soro sanguíneo', 
 'pg/mL', 
 'Laboratório', 
 'Vitaminas', 
 'Clinical', 
 'number', 
 'Medida da vitamina essencial para formação de células vermelhas e função neurológica', 
 false, 
 true, 
 true, 
 'LOINC:2132-9', 
 'International Society for Laboratory Hematology - B12 Guidelines', 
 true),

('Ferritina', 
 'Concentração da proteína de armazenamento de ferro no soro', 
 'ng/mL', 
 'Laboratório', 
 'Minerais', 
 'Clinical', 
 'number', 
 'Medida da principal proteína de reserva de ferro, indicativa dos estoques corporais de ferro', 
 false, 
 false, 
 true, 
 'LOINC:2276-4', 
 'World Health Organization - Iron Deficiency Guidelines', 
 true),

-- MARCADORES INFLAMATÓRIOS
('Proteína C Reativa', 
 'Concentração da proteína de fase aguda no soro', 
 'mg/L', 
 'Laboratório', 
 'Inflamação', 
 'Clinical', 
 'number', 
 'Medida do marcador inespecífico de inflamação e lesão tecidual aguda', 
 false, 
 false, 
 true, 
 'LOINC:1988-5', 
 'Clinical and Laboratory Standards Institute - CRP Guidelines', 
 true),

('VHS', 
 'Velocidade de hemossedimentação dos eritrócitos em uma hora', 
 'mm/h', 
 'Laboratório', 
 'Inflamação', 
 'Clinical', 
 'number', 
 'Medida da velocidade de sedimentação das células vermelhas, indicativa de processos inflamatórios', 
 false, 
 false, 
 true, 
 'LOINC:4537-7', 
 'International Committee for Standardization in Haematology', 
 true);
