-- Query corrigida para popular indicadores padrões 
-- Primeiro execute os scripts necessários se ainda não foram executados:
-- 1. update_indicators_metadata_schema.sql
-- 2. create_admin_system.sql

-- Primeiro, criar as categorias e subcategorias necessárias
INSERT INTO categories (name) VALUES 
('Sinais Vitais'),
('Antropometria'), 
('Laboratório')
ON CONFLICT (name) DO NOTHING;

INSERT INTO subcategories (name, category_id) VALUES 
('Pressão Arterial', (SELECT id FROM categories WHERE name = 'Sinais Vitais')),
('Cardiovascular', (SELECT id FROM categories WHERE name = 'Sinais Vitais')),
('Respiratório', (SELECT id FROM categories WHERE name = 'Sinais Vitais')),
('Termorregulação', (SELECT id FROM categories WHERE name = 'Sinais Vitais')),
('Composição Corporal', (SELECT id FROM categories WHERE name = 'Antropometria')),
('Medidas Lineares', (SELECT id FROM categories WHERE name = 'Antropometria')),
('Medidas Circunferenciais', (SELECT id FROM categories WHERE name = 'Antropometria')),
('Hematologia', (SELECT id FROM categories WHERE name = 'Laboratório')),
('Bioquímica', (SELECT id FROM categories WHERE name = 'Laboratório')),
('Endocrinologia', (SELECT id FROM categories WHERE name = 'Laboratório')),
('Vitaminas', (SELECT id FROM categories WHERE name = 'Laboratório')),
('Minerais', (SELECT id FROM categories WHERE name = 'Laboratório')),
('Inflamação', (SELECT id FROM categories WHERE name = 'Laboratório'))
ON CONFLICT (name, category_id) DO NOTHING;

-- Criar unidades de medida necessárias
INSERT INTO units_of_measure (name, symbol) VALUES 
('Milímetros de Mercúrio', 'mmHg'),
('Batimentos por Minuto', 'bpm'),
('Graus Celsius', '°C'),
('Incursões Respiratórias por Minuto', 'irpm'),
('Percentual', '%'),
('Quilogramas', 'kg'),
('Centímetros', 'cm'),
('Quilogramas por Metro Quadrado', 'kg/m²'),
('Gramas por Decilitro', 'g/dL'),
('Células por Microlitro', 'células/μL'),
('Miligramas por Decilitro', 'mg/dL'),
('Unidades por Litro', 'U/L'),
('Mili Unidades Internacionais por Litro', 'mUI/L'),
('Nanogramas por Decilitro', 'ng/dL'),
('Nanogramas por Mililitro', 'ng/mL'),
('Picogramas por Mililitro', 'pg/mL'),
('Miligramas por Litro', 'mg/L'),
('Milímetros por Hora', 'mm/h')
ON CONFLICT (symbol) DO NOTHING;

-- Inserir indicadores padrões com estrutura correta
INSERT INTO indicators (
  parameter, 
  definition, 
  context, 
  data_type, 
  is_required, 
  is_conditional, 
  is_repeatable, 
  standard_id, 
  source, 
  is_standard,
  doctor_id,
  category_id,
  subcategory_id,
  unit_of_measure_id,
  requires_time,
  requires_date,
  visible,
  visible_to_medics
) VALUES 

-- SINAIS VITAIS
('Pressão Arterial Sistólica', 
 'Medida da pressão máxima exercida pelo sangue nas artérias durante o ciclo cardíaco, correspondente à fase de sístole ventricular', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:8480-6', 
 'Organização Mundial da Saúde - Guidelines for Blood Pressure Measurement', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Pressão Arterial'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mmHg'),
 true,
 true,
 true,
 true),

('Pressão Arterial Diastólica', 
 'Medida da pressão mínima exercida pelo sangue nas artérias durante o ciclo cardíaco, correspondente à fase de diástole ventricular', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:8462-4', 
 'Organização Mundial da Saúde - Guidelines for Blood Pressure Measurement', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Pressão Arterial'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mmHg'),
 true,
 true,
 true,
 true),

('Frequência Cardíaca', 
 'Frequência de contrações do músculo cardíaco por unidade de tempo, geralmente expressa em batimentos por minuto', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:8867-4', 
 'American Heart Association - Heart Rate Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Cardiovascular'),
 (SELECT id FROM units_of_measure WHERE symbol = 'bpm'),
 true,
 true,
 true,
 true),

('Temperatura Corporal', 
 'Medida do grau de calor do corpo humano, indicativa do equilíbrio entre produção e perda de calor corporal', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:8310-5', 
 'International Federation of Clinical Chemistry - Temperature Standards', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Termorregulação'),
 (SELECT id FROM units_of_measure WHERE symbol = '°C'),
 true,
 true,
 true,
 true),

('Frequência Respiratória', 
 'Frequência dos movimentos respiratórios por unidade de tempo, incluindo inspiração e expiração completas', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:9279-1', 
 'European Respiratory Society - Respiratory Rate Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Respiratório'),
 (SELECT id FROM units_of_measure WHERE symbol = 'irpm'),
 true,
 true,
 true,
 true),

('Saturação de Oxigênio', 
 'Medida da porcentagem de hemoglobina ligada ao oxigênio em relação à hemoglobina total no sangue', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:2708-6', 
 'World Health Organization - Pulse Oximetry Training Manual', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Sinais Vitais'),
 (SELECT id FROM subcategories WHERE name = 'Respiratório'),
 (SELECT id FROM units_of_measure WHERE symbol = '%'),
 true,
 true,
 true,
 true),

-- MEDIDAS ANTROPOMÉTRICAS
('Peso Corporal', 
 'Medida da força gravitacional exercida sobre a massa total do corpo humano', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:29463-7', 
 'Organização Mundial da Saúde - Physical Status Assessment', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Antropometria'),
 (SELECT id FROM subcategories WHERE name = 'Composição Corporal'),
 (SELECT id FROM units_of_measure WHERE symbol = 'kg'),
 false,
 true,
 true,
 true),

('Altura', 
 'Medida linear da estatura corporal total em posição anatômica padronizada', 
 'Clinical', 
 'number', 
 true, 
 false, 
 false, 
 'LOINC:8302-2', 
 'International Society for the Advancement of Kinanthropometry', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Antropometria'),
 (SELECT id FROM subcategories WHERE name = 'Medidas Lineares'),
 (SELECT id FROM units_of_measure WHERE symbol = 'cm'),
 false,
 true,
 true,
 true),

('Índice de Massa Corporal', 
 'Índice calculado pela divisão do peso corporal pelo quadrado da altura, utilizado para classificação do estado nutricional', 
 'Clinical', 
 'number', 
 false, 
 true, 
 true, 
 'LOINC:39156-5', 
 'Organização Mundial da Saúde - BMI Classification Standards', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Antropometria'),
 (SELECT id FROM subcategories WHERE name = 'Composição Corporal'),
 (SELECT id FROM units_of_measure WHERE symbol = 'kg/m²'),
 false,
 true,
 true,
 true),

('Circunferência Abdominal', 
 'Medida do perímetro da região abdominal, indicativa de distribuição de gordura corporal central', 
 'Clinical', 
 'number', 
 false, 
 false, 
 true, 
 'LOINC:33747-0', 
 'International Diabetes Federation - Waist Circumference Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Antropometria'),
 (SELECT id FROM subcategories WHERE name = 'Medidas Circunferenciais'),
 (SELECT id FROM units_of_measure WHERE symbol = 'cm'),
 false,
 true,
 true,
 true),

-- EXAMES LABORATORIAIS - HEMATOLOGIA
('Hemoglobina', 
 'Concentração da metaloproteína rica em ferro presente nos glóbulos vermelhos, responsável pelo transporte de oxigênio', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:718-7', 
 'International Council for Standardization in Haematology', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Hematologia'),
 (SELECT id FROM units_of_measure WHERE symbol = 'g/dL'),
 false,
 true,
 true,
 true),

('Hematócrito', 
 'Proporção volumétrica de células vermelhas em relação ao volume total de sangue', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:4544-3', 
 'Clinical and Laboratory Standards Institute', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Hematologia'),
 (SELECT id FROM units_of_measure WHERE symbol = '%'),
 false,
 true,
 true,
 true),

('Contagem de Leucócitos', 
 'Quantificação das células de defesa do organismo presentes no sangue periférico', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:6690-2', 
 'International Society of Laboratory Hematology', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Hematologia'),
 (SELECT id FROM units_of_measure WHERE symbol = 'células/μL'),
 false,
 true,
 true,
 true),

('Contagem de Plaquetas', 
 'Quantificação das células responsáveis pela coagulação sanguínea no sangue periférico', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:777-3', 
 'International Society on Thrombosis and Haemostasis', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Hematologia'),
 (SELECT id FROM units_of_measure WHERE symbol = 'células/μL'),
 false,
 true,
 true,
 true),

-- EXAMES LABORATORIAIS - BIOQUÍMICA  
('Glicemia de Jejum', 
 'Medida da concentração de açúcar no sangue em estado de jejum, indicativo do metabolismo glicídico', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:1558-6', 
 'American Diabetes Association - Standards of Medical Care', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mg/dL'),
 false,
 true,
 true,
 true),

('Hemoglobina Glicada', 
 'Medida do controle glicêmico médio dos últimos 2-3 meses através da glicação da hemoglobina', 
 'Clinical', 
 'number', 
 false, 
 true, 
 true, 
 'LOINC:4548-4', 
 'International Federation of Clinical Chemistry - HbA1c Standardization', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = '%'),
 false,
 true,
 true,
 true),

('Colesterol Total', 
 'Medida da concentração total do esterol presente no plasma sanguíneo, indicativo do perfil lipídico', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:2093-3', 
 'National Cholesterol Education Program Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mg/dL'),
 false,
 true,
 true,
 true),

('HDL Colesterol', 
 'Medida do colesterol transportado por lipoproteínas de alta densidade, considerado protetor cardiovascular', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:2085-9', 
 'European Society of Cardiology - Dyslipidemia Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mg/dL'),
 false,
 true,
 true,
 true),

('LDL Colesterol', 
 'Medida do colesterol transportado por lipoproteínas de baixa densidade, associado ao risco cardiovascular', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:18262-6', 
 'American Heart Association - Cholesterol Management Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mg/dL'),
 false,
 true,
 true,
 true),

('Triglicerídeos', 
 'Medida da concentração de lipídeos simples no plasma, indicativo do metabolismo lipídico', 
 'Clinical', 
 'number', 
 true, 
 false, 
 true, 
 'LOINC:2571-8', 
 'International Atherosclerosis Society - Triglyceride Guidelines', 
 true,
 (SELECT id FROM admins WHERE email = 'renato@timo.com.br'),
 (SELECT id FROM categories WHERE name = 'Laboratório'),
 (SELECT id FROM subcategories WHERE name = 'Bioquímica'),
 (SELECT id FROM units_of_measure WHERE symbol = 'mg/dL'),
 false,
 true,
 true,
 true);

-- Verificar se os dados foram inseridos corretamente
SELECT 
  i.parameter as nome,
  c.name as categoria,
  s.name as subcategoria,
  u.symbol as unidade,
  i.definition as definicao,
  i.standard_id as codigo_loinc
FROM indicators i
JOIN categories c ON i.category_id = c.id
JOIN subcategories s ON i.subcategory_id = s.id
JOIN units_of_measure u ON i.unit_of_measure_id = u.id
WHERE i.is_standard = true
ORDER BY c.name, s.name, i.parameter;
